### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by mastercoms** [Blosc/python-blosc2#89] opened 2023-02-03 19:46 UTC
Hi, on a 3.5MB blosc2 compressed file, I am getting a floating point exception:

```
Starting program: python bot.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 5287]
[New Thread 0x7fffedb21640 (LWP 5288)]

Thread 1 "python" received signal SIGFPE, Arithmetic exception.
___pthread_barrier_wait (barrier=0x555556a12870) at ./nptl/pthread_barrier_wait.c:116

#0  ___pthread_barrier_wait (barrier=0x555556a12870) at ./nptl/pthread_barrier_wait.c:116
#1  0x00007ffff2f7d8b7 in do_job () from /home/ubuntu/.local/share/virtualenvs/gamebot-s1LiBexb/lib/python3.10/site-packages/blosc2/blosc2_ext.cpython-310-x86_64-linux-gnu.so
#2  0x00007ffff2f7ee3f in blosc_run_decompression_with_context () from /home/ubuntu/.local/share/virtualenvs/gamebot-s1LiBexb/lib/python3.10/site-packages/blosc2/blosc2_ext.cpython-310-x86_64-linux-gnu.so
#3  0x00007ffff2f7f404 in blosc2_decompress () from /home/ubuntu/.local/share/virtualenvs/gamebot-s1LiBexb/lib/python3.10/site-packages/blosc2/blosc2_ext.cpython-310-x86_64-linux-gnu.so
#4  0x00007ffff2f5ed29 in __pyx_pf_6blosc2_10blosc2_ext_4decompress.constprop.0 () from /home/ubuntu/.local/share/virtualenvs/gamebot-s1LiBexb/lib/python3.10/site-packages/blosc2/blosc2_ext.cpython-310-x86_64-linux-gnu.so
#5  0x00005555556afb5e in ?? ()
#6  0x00005555556a67db in _PyObject_MakeTpCall ()
#7  0x000055555569f48e in _PyEval_EvalFrameDefault ()
#8  0x00005555556b03ac in _PyFunction_Vectorcall ()
#9  0x0000555555699005 in _PyEval_EvalFrameDefault ()
#10 0x00005555556b03ac in _PyFunction_Vectorcall ()
#11 0x000055555569914a in _PyEval_EvalFrameDefault ()
#12 0x00005555556b03ac in _PyFunction_Vectorcall ()
#13 0x00005555556a5a0d in _PyObject_FastCallDictTstate ()
#14 0x00005555556ba594 in ?? ()
#15 0x00005555556a6b8b in ?? ()
#16 0x00005555556befcb in PyObject_Call ()
#17 0x000055555569b3b0 in _PyEval_EvalFrameDefault ()
#18 0x00005555556b03ac in _PyFunction_Vectorcall ()
#19 0x00005555556a5a0d in _PyObject_FastCallDictTstate ()
#20 0x00005555556ba594 in ?? ()
#21 0x00005555556a677c in _PyObject_MakeTpCall ()
#22 0x000055555569fe1c in _PyEval_EvalFrameDefault ()
#23 0x00005555556b03ac in _PyFunction_Vectorcall ()
#24 0x00005555556a5a0d in _PyObject_FastCallDictTstate ()
#25 0x00005555556ba594 in ?? ()
#26 0x00005555556a677c in _PyObject_MakeTpCall ()
#27 0x000055555569fe1c in _PyEval_EvalFrameDefault ()
#28 0x00005555556cd900 in ?? ()
#29 0x00007ffff755762e in ?? () from /usr/lib/python3.10/lib-dynload/_asyncio.cpython-310-x86_64-linux-gnu.so
#30 0x00007ffff7557444 in ?? () from /usr/lib/python3.10/lib-dynload/_asyncio.cpython-310-x86_64-linux-gnu.so
#31 0x00005555556a67db in _PyObject_MakeTpCall ()
#32 0x000055555583fb12 in ?? ()
```

```
$ uname -a
Linux vps-3143fc89 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

```
$ apt info python3.10
Package: python3.10
Version: 3.10.6-1~22.04.2
Priority: important
Section: python
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Matthias Klose <doko@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 635 kB
Depends: python3.10-minimal (= 3.10.6-1~22.04.2), libpython3.10-stdlib (= 3.10.6-1~22.04.2), media-types | mime-support
Suggests: python3.10-venv, python3.10-doc, binutils
Breaks: python3-all (<< 3.6.5~rc1-1), python3-dev (<< 3.6.5~rc1-1), python3-venv (<< 3.6.5-2)
Task: minimal, server-minimal
Download-Size: 497 kB
APT-Manual-Installed: yes
APT-Sources: http://nova.clouds.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
Description: Interactive high-level object-oriented language (version 3.10)
 Python is a high-level, interactive, object-oriented language. Its 3.10 version
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.
```

```
$ python -VV
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

I have the core dump file and file which causes this on request.

**Comment by FrancescAlted** [comment] 2023-02-03 20:24
Hmm, looks like it is a thread-related issue.  Mind to send a minimal python script reproducing this?

**Comment by mastercoms** [comment] 2023-02-03 21:03
```python
from blosc2 import decompress

with open("responses.db", "rb") as db_file:
    data = decompress(db_file.read())
    print(data[:1000])
```

**Comment by mastercoms** [comment] 2023-02-03 21:05
It seems to not happen with a version of Python compiled with an older GCC.

Works:

```
$ python3.10 -VV
Python 3.10.9 (main, Jan 28 2023, 19:03:24) [GCC 9.4.0]
```

Doesn't work:

```
$ python3.10 -VV
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

**Comment by mastercoms** [comment] 2023-02-04 12:15
This is the file that causes it by the way: [responses.txt](https://github.com/Blosc/python-blosc2/files/10608596/responses.txt)

**Comment by FrancescAlted** [comment] 2023-02-07 16:57
I have tried out the file on different scenarios (Intel with Linux, Mac with M1) and I am always getting a sane result from the binary wheels:

```
b'{"_default":{"1":{"processed_text":"abaddon","original_text":"Abaddon.","response_link":"https://static.wikia.nocookie.net/dota2_gamepedia/images/8/89/Vo_abaddon_abad_spawn_01.mp3","hero_name":"Abaddon"},"2":{"processed_text":"lord of avernus","original_text":"Lord of Avernus.","response_link":"https://static.wikia.nocookie.net/dota2_gamepedia/images/0/05/Vo_abaddon_abad_spawn_02.mp3","hero_name":"Abaddon"},"3":{"processed_text":"this place appears like a vision in the mist","original_text":"This place appears like a vision in the mist.","response_link":"https://static.wikia.nocookie.net/dota2_gamepedia/images/1/1b/Vo_abaddon_abad_spawn_03.mp3","hero_name":"Abaddon"},"4":{"processed_text":"from house avernus i set forth","original_text":"From House Avernus, I set forth.","response_link":"https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f9/Vo_abaddon_abad_spawn_05.mp3","hero_name":"Abaddon"},"5":{"processed_text":"the fog of war is no match for the mist of fate","original_text'
```

To discard any possible effect on modern compilers, I have tried compiling with modern gcc (12.2.1) and clang (15.0.6), but I was unable to reproduce the issue.

I am closing this for now.  In case you find a way to reproduce it (with a self-contained script preferably), please reopen.

**Closed by FrancescAlted** 2023-02-07 16:57 UTC

**Comment by mastercoms** [comment] 2023-02-08 02:11
Do you have any ideas on how to diagnose any environment differences that may be present on my machine?
